### ISSUE TITLE
Use MessageBoxW instead of MessageBoxA

### ISSUE THREAD

**Issue by retep998** [wesleywiser/rust_messagebox_hello_world#1]
By using `MessageBoxA` you are basically subjecting your program to the whims of whatever the current code page is on Windows, which is never UTF-8. You should instead use `MessageBoxW` as demonstrated in the example in winapi's [readme](https://github.com/retep998/winapi-rs#example).

**Comment by wesleywiser** [comment]
Thank you for pointing this out. I'll address this in the next blog post

**Comment by pravic** [comment]
Due to weird state of UTF16 support in Rust, it is easier to use the ANSI functions, at least when we know that our rust strings are compatible with ASCII.

**Comment by retep998** [comment]
What weird state of UTF-16? `OsString` provides very solid support for converting between wide strings and WTF-8.

Also, the code pages on Windows are not necessarily a superset of ASCII, so please don't claim that plain ASCII text can use the A versions safely, because it can't.

**Comment by pravic** [comment]
Look at your example: `let wide: Vec<u16> = OsStr::new(msg).encode_wide().chain(once(0)).collect();`
Is it not a weird? :smiling_imp: 

> the code pages on Windows are not necessarily a superset of ASCII

Any proof link about that?

**Comment by retep998** [comment]
That's not weird, That's just a bit unwieldy, and only because std doesn't provide a convenient method for it. If you were using `wio` you would just do `msg.to_wide_null()`.

**Comment by retep998** [comment]
> Any proof link about that?

@pravic For example Shift JIS which is extensively used in Japanese Windows replaces `\` with `¥`.

**Comment by wesleywiser** [comment]
I've written a new post about this [here](https://wesleywiser.github.io/post/rust-windows-message-box-unicode/). The code is in this repo under the `unicode` branch. 

I'm closing this now.
